name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo dependencies
      uses: Swatinem/rust-cache@v2

    - name: Format check
      run: cargo fmt -- --check
      working-directory: .  # Explicitly ensure it's in the correct directory

    - name: Lint with Clippy
      run: cargo clippy -- -D warnings
      working-directory: .

    - name: Run tests
      run: cargo test --verbose
      working-directory: .

    - name: Build release
      run: cargo build --release
      working-directory: .
